targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        enabled: true
        options:
          auto_register: true

      freezed:freezed:
        enabled: true
        options:
          # Run build_runner once to generate the code.
          # If the generated file is not found on the first run,
          # run it twice: `flutter pub run build_runner build --delete-conflicting-outputs`

      json_serializable:
        enabled: true

      auto_route_generator:autoRouteGenerator:
        enabled: true
        options:
          # Routes generation options
