// File generated by FlutterFire CLI.
// PLACEHOLDER FILE - Replace with actual Firebase configuration
//
// To generate the actual file, run:
// flutterfire configure
//
// Make sure you have Firebase CLI and FlutterFire CLI installed:
// npm install -g firebase-tools
// dart pub global activate flutterfire_cli
//
// Then run: flutterfire configure
// This will create a Firebase project and generate the proper configuration

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCifvQ8HIqt3dldNlZlEHyYV3U387mHYWc',
    appId: '1:228424606341:web:67cd9aa5fa23de7eb9ffec',
    messagingSenderId: '228424606341',
    projectId: 'admob-app-id-7101158818',
    authDomain: 'admob-app-id-7101158818.firebaseapp.com',
    databaseURL: 'https://admob-app-id-7101158818.firebaseio.com',
    storageBucket: 'admob-app-id-7101158818.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwV1PKryc0TI5u2t_zLaSr39Qu_EPvumM',
    appId: '1:228424606341:android:84145c0745acc791b9ffec',
    messagingSenderId: '228424606341',
    projectId: 'admob-app-id-7101158818',
    databaseURL: 'https://admob-app-id-7101158818.firebaseio.com',
    storageBucket: 'admob-app-id-7101158818.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZqq0_un3e_Li_WYYbzh0m4m351hMhE_o',
    appId: '1:228424606341:ios:1502c606d76cb1acb9ffec',
    messagingSenderId: '228424606341',
    projectId: 'admob-app-id-7101158818',
    databaseURL: 'https://admob-app-id-7101158818.firebaseio.com',
    storageBucket: 'admob-app-id-7101158818.firebasestorage.app',
    iosBundleId: 'org.congtruyen.bookingDemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZqq0_un3e_Li_WYYbzh0m4m351hMhE_o',
    appId: '1:228424606341:ios:1502c606d76cb1acb9ffec',
    messagingSenderId: '228424606341',
    projectId: 'admob-app-id-7101158818',
    databaseURL: 'https://admob-app-id-7101158818.firebaseio.com',
    storageBucket: 'admob-app-id-7101158818.firebasestorage.app',
    iosBundleId: 'org.congtruyen.bookingDemoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCifvQ8HIqt3dldNlZlEHyYV3U387mHYWc',
    appId: '1:228424606341:web:04e13e3338a3a413b9ffec',
    messagingSenderId: '228424606341',
    projectId: 'admob-app-id-7101158818',
    authDomain: 'admob-app-id-7101158818.firebaseapp.com',
    databaseURL: 'https://admob-app-id-7101158818.firebaseio.com',
    storageBucket: 'admob-app-id-7101158818.firebasestorage.app',
  );

}